### ISSUE TITLE
Impossível carregar complemento 'lftools' Devido a um erro ao chamar o método Class Factory(). 

### ISSUE THREAD

**Issue by VlamirNogueira** [LEOXINGU/lftools#11]
Olá, Leandro.
Meu LF tools não está rodando.
Aparece o seguinte erro:
.
Impossível carregar complemento 'lftools' Devido a um erro ao chamar o método Class Factory(). 

ImportError: numpy.core.multiarray failed to import 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lftools\__init__.py", line 38, in classFactory
    from .lftools import LFToolsPlugin
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lftools\lftools.py", line 41, in 
    from .lftools_provider import LFToolsProvider
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lftools\lftools_provider.py", line 49, in 
    from .processing_provider.Rast_Bands2RGB import Bands2RGB
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lftools\processing_provider\Rast_Bands2RGB.py", line 47, in 
    from osgeo import osr, gdal_array, gdal
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\site-packages\osgeo\gdal_array.py", line 13, in 
    from . import _gdal_array
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: numpy.core.multiarray failed to import

Versão do Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Versão do QGIS: 3.30.2-'s-Hertogenbosch 's-Hertogenbosch, 0992b533 

Caminho do Python:
C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HTML_Generator-main
C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoINCRA
C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\contour
C:/PROGRA~1/QGIS33~1.2/apps/qgis/./python
C:/Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.2/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS33~1.2\apps\grass\grass82\etc\python
C:\WINDOWS\system32
C:\Program Files\QGIS 3.30.2\bin\python39.zip
C:\PROGRA~1\QGIS33~1.2\apps\Python39\DLLs
C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib
C:\Program Files\QGIS 3.30.2\bin
C:\Users\Usuário\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS33~1.2\apps\Python39
C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\Usuário\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
C:\Users\Usuário\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools
C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\excel_sync\libs\xlrd-1.2.0-py2.py3-none-any.whl
C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\excel_sync\libs\xlwt-1.3.0-py2.py3-none-any.whl
C:\Users\Usuário\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HCMGIS/forms
C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inde
C:\Users\Usuário\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\kmltools\libs
C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web
C:\Users\Usuário\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\rvt-qgis

**Comment by VlamirNogueira** [comment]
Consegui resolver.
Rodei: pip install numpy --upgrade
Ele me pediu ara fazer antes:  python3.exe -m pip install --upgrade pip
Está rodando.

**Comment by LEOXINGU** [comment]
Olá @VlamirNogueira !

Excelente que já resolveu!
