### ISSUE TITLE
Erro ao instalar

### ISSUE THREAD

**Issue by AntonioTLeandro** [LEOXINGU/lftools#12]
![Error lftools](https://github.com/LEOXINGU/lftools/assets/47145799/1fd08321-14fe-458f-9916-fb41108b1505)

Segue imagem do erro ao instalar o complemento.

**Comment by LEOXINGU** [comment]
Olá Antonio,
Você está usando MacOS? Tenta atualizar primeiro seu QGIS para a versão LTR. Segue um tutorial com mais detalhes: https://www.youtube.com/watch?v=QeonUQigYR8

Se estiver com o Mac, provavelmente vai precisar instalar a biblioteca PIL. Nesse vídeo a gente ensina como instalar: https://www.youtube.com/watch?v=dFw5klenKCE

**Comment by AntonioTLeandro** [comment]
Estou usando o WIN 11

**Comment by LEOXINGU** [comment]
Também estou usando o W11, parece-me que o problema esteja na biblioteca numpy ou gdal. Elas já vem instaladas junto com o QGIS, talvez seja problema na instalação do seu QGIS.
