### ISSUE TITLE
Calculate polygon angles

### ISSUE THREAD

**Issue by Fertuesta25** [LEOXINGU/lftools#3]
The algorithm to calculate polygon angles does not work, it generates the following error:
Traceback (most recent call last):
File "C:\Users/criss/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lftools\processing_provider\Vect_PolygonAngles.py", line 185, in processAlgorithm
dd2dms(pntsDic[ponto]['alfa_int']),
TypeError: dd2dms() missing 1 required positional argument: 'n_digits'

Execution failed after 0.10 segundos

**Comment by LEOXINGU** [comment]
Thank you for your feedback.
The new version 1.3.7 of the LFTools plugin is now available here on GitHub with the correction of the polygon angle calculation tool.
It has also already been submitted to the QGIS Official Repository for approval and will soon be available there.
See the result:
![image](https://user-images.githubusercontent.com/25651083/139837061-d296c4a0-ef97-4822-80e5-d2190fe983ac.png)

**Comment by ElvisKlinton** [comment]
El algoritmos de "calculate polygon angles" me sale un error

![image](https://user-images.githubusercontent.com/106482200/178651059-d7476217-f77f-41b6-a522-9677939bc029.png)


Solo es posible cuando ejecuto en una capa de polígono TEMPORAL. Como podría realizar para un poligono que ya  se ha  creado anteriormente

**Comment by LEOXINGU** [comment]
Hola Elvis,

Logré resolver el error. Por favor, pido la posibilidad de que hagas algunas pruebas del algoritmo primero, para poder subir una nueva versión en el repositorio oficial de QGIS más tarde.
Aquí hay un tutorial que enseña cómo descargar el complemento directamente desde GitHub e instalarlo con un archivo ZIP: https://youtu.be/cQi2Qxnvh-8

**Comment by ElvisKlinton** [comment]
Muy buen dia!!
acabo de instalar el complemento, pero me  sale este error
[image: image.png]
