### ISSUE TITLE
Calcula los ángulos del polígono

### ISSUE THREAD

**Issue by ElvisKlinton** [LEOXINGU/lftools#5]
El algoritmos de "calcular ángulos poligonales" me sale un error

![image](https://user-images.githubusercontent.com/106482200/179262187-26d315cb-1aa7-4cf3-a5c5-da639859ab35.png)
Solo es posible cuando se ejecuta en una capa de polígono TEMPORAL. Como podría realizar para un polígono que ya se ha creado anteriormente

**Comment by LEOXINGU** [comment]
Hola Elvis,

Logré resolver el error. Por favor, pido la posibilidad de que hagas algunas pruebas del algoritmo primero, para poder subir una nueva versión en el repositorio oficial de QGIS más tarde.
Aquí hay un tutorial que enseña cómo descargar el complemento directamente desde GitHub e instalarlo con un archivo ZIP: https://youtu.be/cQi2Qxnvh-8

**Comment by LEOXINGU** [comment]
O bug foi resolvido. 
Por favor, baixe novamente o plugin do repositório oficial do QGIS.

**Comment by ElvisKlinton** [comment]
Perfecto! Mil gracias.........! 
![image](https://user-images.githubusercontent.com/106482200/181846749-9a8c9210-def7-4014-9230-cc6a28f2add9.png)
