### ISSUE TITLE
Tooltip missing image with distant pictures on a network folder

### ISSUE THREAD

**Issue by Fabien98** [LEOXINGU/lftools#6]
First, thanks for this wonderful and multifonction plugin!

With the Reambulation/Photos with geotag tool
It seems that when you process pictures on a networked Windows drive, the tooltip is not rendered.
No problem when the folder is on a local drive.

Example
When the picture folder is located on
`\\ZZZ356FA11\folder\PictureFolder\`
then in the tooltip properties
`<img src="file:///[%path%]" width="450">`
is not rendered on map

It seems like a QGIS bug and not specifically a plugin bug but do you have any hints in tooltip redaction to make this working even on networked drive?
(and making this function more resilient?)

**Comment by Fabien98** [comment]
I finally found the correct syntax with the image in tooltip..

- for LOCAL pictures: **3/// after file:**

`<img src="file:///[%path%]" width="450">`

- for DISTANT pictures: **2// after file:**

`<img src="file://[%path%]" width="450">`

I close the issue

**Comment by LEOXINGU** [comment]
@Fabien98 , thank you for the tip!
I implemented an improvement in the LFTools code and it is now working for both cases.
