### ISSUE TITLE
Icon LF tools não aparece na barra e o oplugin está instalado e seleccionado

### ISSUE THREAD

**Issue by psygoblin666** [LEOXINGU/lftools#8]
Bom dia Leandro,

Em primeiro lugar os meus parabens pelo desenvoilvimento do plugin. Estou a tentar aceder ao plugin, mas apenas me aparece as ferramentas nas ferramentas de processamento. O botão do INDA não me aparece nas barras superiores e já tentei de tudo, sem sucesso.

Os melhores cumprimentos,
Luis Carlos Pereira

**Comment by LEOXINGU** [comment]
Olá Carlos!
Obrigado!
O plugin INDE foi desenvolvido pelo meu amigo Julierme Pinheiro. Ou seja, ele é outro plugin e não faz parte do LFTools.
Segue um tutorial sobre o plugin INDE: [https://youtu.be/N7895sz7ITc](https://youtu.be/N7895sz7ITc)
E o repositório dele é o seguinte: https://github.com/indeOWS/INDE/tree/1.0
